### ISSUE TITLE
the pauseMissionExecution does not trigger the completion callback

### ISSUE THREAD

**Issue by xxmaestroxx** [dji-sdk/Mobile-SDK-Android#55]
When i called the pauseMissionExecution method on the mission manager the completion callback is not called, neither with error or without an error, but the mission is paused, so i'm wasted a lot of time to wait for the response until i noticed that the mission is stopped correctly and can be resumed correctly but in both ways the callback is not triggered.

Regards 
Using: 3.4 Android SDK

**Comment by SilverChangjian** [comment]
Thanks for reporting this bug. This is a bug fixed in 3.4.1, could you please check this bug in 3.4.1? Thank you,

**Comment by xxmaestroxx** [comment]
Hey thanks for quick reply,

I will check and inform you.

**Comment by xxmaestroxx** [comment]
Checked it directly and the DJICompletionCallback for the pause and resume method is not called. So i stuck at this point when i'm waiting for the callback!

**Comment by jtuchek** [comment]
I am also experiencing this in SDK v3.4.0 and 3.4.1.

This only seems to occur when using certain types of missions.

Working:
-Waypoint
-Custom (takeoff, land, shoot photo, goto, gimbal adjust)

Not Working:
-Custom that contains a DJIWaypointStep

**Comment by wenqianqiao** [comment]
For the waypoint Mission, I think it has been solved in the 3.4.1.  What kind of the Mission are you running when you face this problem ? From my test I can get the callback from the pause and resume function in the Missionmanager. 

Besides, for jtuchek, 
For the DJIWaypointStep in the CutomMission, we found there is no callback for that. I guess it is the problem inside the SDK. We have already recorded them. Thank you for your feedback.

**Comment by xxmaestroxx** [comment]
I am using the custom mission. Thanks for you investigations!

**Comment by jtuchek** [comment]
@wenqianqiao thanks for the response, although I'm not sure what it means.

Is that something that is recorded as a bug and being fixed, or not considered broken?

Should I find my own mechanism for determining pause/play off of aircraft velocity.. or is it something being fixed in an upcoming release?

**Comment by xxmaestroxx** [comment]
Hey DJI,

what is the status of this issue?

Regards
Maestro

**Comment by dji-dev** [comment]
I think for the custom mission we have already solved this in the 3.5.1.  Could you please check and see if that problem is solved ?

**Comment by xxmaestroxx** [comment]
Hey thanks for the quick response, 
but unfortunately i still have the problem. 
Until yesterday evening i used the 3.5.1 SDK (Which isn't anymore available on github) but by using this sdk neither the pauseMissionCallback is work nor the stopMissionCallback is working and moreover the gimbal attitude step is not working.

So i had to switch back to 3.5, to have the gimbal attitude step working again.

When can we expect a next release with some bugfixes from you side?

Many thanks and Regards
Maestro

**Comment by talobin** [comment]
Will go ahead and close this ticket as current version (4.3.2) should have a fix for this already.
Also, for mission related task, please check out the new `MissionControl` class.
Please feel free to reopen if the problem still exists.
Thanks!
